Socint 221 cc UI cucumber tests
ONSdigital/sdc-int-cc-cucumber pull request #4
Opened 2021-11-11 08:44 UTC by SteveScorfield

This is for ticket https://collaborate2.ons.gov.uk/jira/browse/SOCINT-221

2021-11-11 16:13 UTC, rpcatling requested changes
some comments

2021-11-12 09:11 UTC, SteveScorfield commented on src/test/java/uk/gov/ons/ctp/integration/cccucumber/glue/CcSteps.java
> +  private void sendInboundEvents() throws Exception {
I moved it to the bottom.

2021-11-12 09:11 UTC, SteveScorfield commented on src/test/java/uk/gov/ons/ctp/integration/cccucumber/glue/CcSteps.java
> +  private String caseNotFoundErrorMsg =
Agreed. These have been moved over.

2021-11-12 09:11 UTC, SteveScorfield commented on src/test/java/uk/gov/ons/ctp/integration/cccucumber/glue/CcSteps.java
> +  private String addressNotFound =
Agreed. These have been moved over.

2021-11-12 09:11 UTC, SteveScorfield commented on src/test/resources/features/SurveyEnquiryLine.feature
>    @SelPostcodeSearch @Setup @TearDown
Forgot to add the tags. They are now added.

2021-11-12 09:11 UTC, SteveScorfield commented on src/test/resources/features/SurveyEnquiryLine.feature
> +  @SelPostcodeSearch @Setup @TearDown
As above.

2021-11-12 09:11 UTC, SteveScorfield commented on src/test/resources/features/SurveyEnquiryLine.feature
> +  @SelPostcodeSearch @Setup @TearDown
As above.

2021-11-12 10:11 UTC, SteveScorfield commented on src/test/resources/features/SurveyEnquiryLine.feature
> +  	Given The SEL operator is in CCUI find case page
First 6 are now as part of initial setup.

2021-11-12 10:11 UTC, SteveScorfield commented on src/test/resources/features/SurveyEnquiryLine.feature
> +    Given The SEL operator is in CCUI find case page
First 6 are now as part of initial setup.

2021-11-12 10:11 UTC, SteveScorfield commented on src/test/resources/features/SurveyEnquiryLine.feature
> +    Given The SEL operator is in CCUI find case page
First 6 are now as part of initial setup.

2021-11-12 11:04 UTC, rpcatling commented
A few more things to change as discussed on the slack channel
- make hook for setup rather than private method , and update feature file accordingly
- fix naming convention for static final Strings
- add unique default CaseID UUID to avoid conflict with RHcuc tests

2021-11-12 11:15 UTC, rpcatling approved these changes

2021-11-12 12:15 UTC, PeterBochel approved these changes

2021-11-12 12:17 UTC, merged